// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2RaEG6vcU9Js5SgjBbtffmG5voksPIJ8',
    appId: '1:550429868908:web:d96730cd4836398b34e949',
    messagingSenderId: '550429868908',
    projectId: 'pathway-b9fb3',
    authDomain: 'pathway-b9fb3.firebaseapp.com',
    storageBucket: 'pathway-b9fb3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrYSO19KNlyIbrkYn0bZ7mGyvyFMsajiU',
    appId: '1:550429868908:android:622ad74d7dc42ecf34e949',
    messagingSenderId: '550429868908',
    projectId: 'pathway-b9fb3',
    storageBucket: 'pathway-b9fb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlLWqznMnnuioza0QULsuz5hi6Ad5-TdM',
    appId: '1:550429868908:ios:8c2295712c94f3f834e949',
    messagingSenderId: '550429868908',
    projectId: 'pathway-b9fb3',
    storageBucket: 'pathway-b9fb3.appspot.com',
    iosBundleId: 'com.example.pathWayFlu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlLWqznMnnuioza0QULsuz5hi6Ad5-TdM',
    appId: '1:550429868908:ios:d1e21656c7d3175834e949',
    messagingSenderId: '550429868908',
    projectId: 'pathway-b9fb3',
    storageBucket: 'pathway-b9fb3.appspot.com',
    iosBundleId: 'com.example.pathWayFlu.RunnerTests',
  );
}
